on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@master
      - run: go test github.com/ay0o/pricetopus/internal/parser
      - uses: docker/build-push-action@master
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: ay0o/pricetopus
            tags: latest
